name: Deploy Preview PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    environment:
      name: github-pages-preview
      url: https://antoinegreuzard.github.io/chess-game/pr-${{ github.event.pull_request.number }}/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build with base path
        run: |
          export BASE_PATH=/chess-game/pr-${{ github.event.pull_request.number }}/
          npm run build

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: pr-${{ github.event.pull_request.number }}
          publish_branch: gh-pages
